/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ESTIVEN
 */
public class interfaz_memorabble extends javax.swing.JFrame {

    /**
     * Creates new form interfaz_memorabble
     */
    public interfaz_memorabble() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_como_jugar = new javax.swing.JButton();
        btn_jugar = new javax.swing.JButton();
        lbl_titulo = new javax.swing.JLabel();
        btn_para_que_sirve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(90, 146, 45));

        btn_como_jugar.setText("¿Cómo jugar?");
        btn_como_jugar.setBorderPainted(false);
        btn_como_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_como_jugarActionPerformed(evt);
            }
        });

        btn_jugar.setText("JUGAR");
        btn_jugar.setBorder(null);
        btn_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jugarActionPerformed(evt);
            }
        });

        lbl_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/memorabble.jpg"))); // NOI18N

        btn_para_que_sirve.setText("¿Para qué sirve?");
        btn_para_que_sirve.setBorderPainted(false);
        btn_para_que_sirve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_para_que_sirveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_titulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_como_jugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_para_que_sirve)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btn_jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_como_jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_para_que_sirve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_como_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_como_jugarActionPerformed
        JOptionPane.showMessageDialog(null,"Instrucciones: "
        + "\n" + "* Saldrán unas figuras con distintos colores y después de unos segundos desaparecerán."
        + "\n" + "* Después saldrá una pregunta."
        + "\n" + "* La pregunta te indicara, que debes pulsar sobre una ficha que cumpla con la condición dada."
        + "\n" + "* ¡OJO! Es posible  que haya que pulsar más de una ficha..."
        + "\n" + "* Es importante que memorices formas, colores y posición de cada ficha.");
    }//GEN-LAST:event_btn_como_jugarActionPerformed

    private void btn_para_que_sirveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_para_que_sirveActionPerformed
       JOptionPane.showMessageDialog(null,"Un juego que te permite entrenar tu capacidad de codificación y recuerdo de información visual y espacial. \n"
               + "Este tipo de habilidades es relevante en la práctica de algunos deportes, el reconocimiento de caras o para \nrecordar dónde guardamos nuestras cosas.");
    }//GEN-LAST:event_btn_para_que_sirveActionPerformed

    private void btn_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jugarActionPerformed
       String nombre=JOptionPane.showInputDialog("Digite su nombre para continúar: ");
       JOptionPane.showMessageDialog(null,"Buen juego "+nombre);
       dispose();
       interfaz_jugable ij=new interfaz_jugable();
       ij.setVisible(true);
       
       
    }//GEN-LAST:event_btn_jugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_memorabble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_memorabble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_memorabble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_memorabble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_memorabble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_como_jugar;
    private javax.swing.JButton btn_jugar;
    private javax.swing.JButton btn_para_que_sirve;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
